name: My First Workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
            
          - name: Print Hello World
            run: echo "Hello World"
          
          - name: List Files
            run: ls
          
          - name: Read File
            run: cat README.md